<a href="https://colab.research.google.com/github/ddodds42/DS-Unit-1-Build/blob/master/Imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import r2_score

%matplotlib inline

df = pd.read_excel('PWGI Voice Acct NANs.xlsx')
df.head()

     Country Name Country Code  1972  1973  1974  ...  2015  2016  2017  2018  2019
0     Afghanistan          AFG   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN
1         Albania          ALB   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN
2         Algeria          DZA   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN
3  American Samoa          ASM   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN
4         Andorra          ADO   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN

[5 rows x 50 columns]

In [0]:
prestrip = df.T

prestrip.head()

                      0        1        2    ...          212     213       214
Country Name  Afghanistan  Albania  Algeria  ...  Yemen, Rep.  Zambia  Zimbabwe
Country Code          AFG      ALB      DZA  ...          YEM     ZMB       ZWE
1972                  NaN      NaN      NaN  ...          NaN     NaN       NaN
1973                  NaN      NaN      NaN  ...          NaN     NaN       NaN
1974                  NaN      NaN      NaN  ...          NaN     NaN       NaN

[5 rows x 215 columns]

In [0]:
preimputable = prestrip.iloc[2:,:]
preimputable.head()

      0    1    2    3    4    5    6    ...  208  209  210  211  212  213  214
1972  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1973  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1974  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1975  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1976  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[5 rows x 215 columns]

In [0]:
imputable = preimputable

In [0]:
imputable.index = pd.to_datetime(preimputable.index, format='%Y')
imputable.head()

            0    1    2    3    4    5    ...  209  210  211  212  213  214
1972-01-01  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN
1973-01-01  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN
1974-01-01  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN
1975-01-01  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN
1976-01-01  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN  NaN

[5 rows x 215 columns]

In [0]:
imputed = imputable.astype(float).interpolate(method='time', limit_direction="both")
imputed.head()

                 0         1         2    ...       212       213       214
1972-01-01 -1.896506 -0.756354 -1.267226  ... -0.679888 -0.396257 -0.618496
1973-01-01 -1.896506 -0.756354 -1.267226  ... -0.679888 -0.396257 -0.618496
1974-01-01 -1.896506 -0.756354 -1.267226  ... -0.679888 -0.396257 -0.618496
1975-01-01 -1.896506 -0.756354 -1.267226  ... -0.679888 -0.396257 -0.618496
1976-01-01 -1.896506 -0.756354 -1.267226  ... -0.679888 -0.396257 -0.618496

[5 rows x 215 columns]

In [0]:
mergeable = imputed.T

mergeable.head()

   1972-01-01  1973-01-01  1974-01-01  ...  2017-01-01  2018-01-01  2019-01-01
0   -1.896506   -1.896506   -1.896506  ...   -1.161956   -1.161956   -1.161956
1   -0.756354   -0.756354   -0.756354  ...    0.163576    0.163576    0.163576
2   -1.267226   -1.267226   -1.267226  ...   -0.928584   -0.928584   -0.928584
3    0.473212    0.473212    0.473212  ...    1.044215    1.044215    1.044215
4    1.540904    1.540904    1.540904  ...    1.189276    1.189276    1.189276

[5 rows x 48 columns]

In [0]:
# mergeable.describe()
mergeable.iloc[:,0:1].describe()

       1972-01-01
count  214.000000
mean     0.003808
std      0.997385
min     -2.088474
25%     -0.742515
50%     -0.070255
75%      0.931983
max      1.692598

In [0]:
downloadable = pd.concat([df.iloc[:,0:1],mergeable], axis=1)
downloadable

              Country Name  ...  2019-01-01 00:00:00
0              Afghanistan  ...            -1.161956
1                  Albania  ...             0.163576
2                  Algeria  ...            -0.928584
3           American Samoa  ...             1.044215
4                  Andorra  ...             1.189276
..                     ...  ...                  ...
210  Virgin Islands (U.S.)  ...             0.826263
211     West Bank and Gaza  ...            -0.848456
212            Yemen, Rep.  ...            -1.335908
213                 Zambia  ...            -0.144867
214               Zimbabwe  ...            -1.277444

[215 rows x 49 columns]

In [0]:
downloadable.isna().sum()

Country Name           0
1972-01-01 00:00:00    1
1973-01-01 00:00:00    1
1974-01-01 00:00:00    1
1975-01-01 00:00:00    1
1976-01-01 00:00:00    1
1977-01-01 00:00:00    1
1978-01-01 00:00:00    1
1979-01-01 00:00:00    1
1980-01-01 00:00:00    1
1981-01-01 00:00:00    1
1982-01-01 00:00:00    1
1983-01-01 00:00:00    1
1984-01-01 00:00:00    1
1985-01-01 00:00:00    1
1986-01-01 00:00:00    1
1987-01-01 00:00:00    1
1988-01-01 00:00:00    1
1989-01-01 00:00:00    1
1990-01-01 00:00:00    1
1991-01-01 00:00:00    1
1992-01-01 00:00:00    1
1993-01-01 00:00:00    1
1994-01-01 00:00:00    1
1995-01-01 00:00:00    1
1996-01-01 00:00:00    1
1997-01-01 00:00:00    1
1998-01-01 00:00:00    1
1999-01-01 00:00:00    1
2000-01-01 00:00:00    1
2001-01-01 00:00:00    1
2002-01-01 00:00:00    1
2003-01-01 00:00:00    1
2004-01-01 00:00:00    1
2005-01-01 00:00:00    1
2006-01-01 00:00:00    1
2007-01-01 00:00:00    1
2008-01-01 00:00:00    1
2009-01-01 00:00:00    1
2010-01-01 00:00:00    1
2011-01-01 00:00:00    1
2012-01-01 00:00:00    1
2013-01-01 00:00:00    1
2014-01-01 00:00:00    1
2015-01-01 00:00:00    1
2016-01-01 00:00:00    1
2017-01-01 00:00:00    1
2018-01-01 00:00:00    1
2019-01-01 00:00:00    1
dtype: int64

In [0]:
downloadable.to_excel("PWGI_Voice_Acct_imp.xlsx")